### ISSUE TITLE
German ( vertseckte Trojnaer  ) ich unterstelle es euch !!!!!

### ISSUE THREAD

**Issue by Knopfan** [dotnet/docs.de-de#103]
[Hier Feedback eingeben]
Ich habe ein I7-8750 / 16GB-Ram / GTX1050 4 GB ! 50.000 DLS
Eure Seite https://docs.microsoft.com die ich gerne besuche hatte lagtt wie sau .
Die ist fast unbrauchbar von Seitenaufbau bis jeder Benutzung laggg!
Wenn ich runterscrollen will muß ich 5 Sekunden warten bis es weiter geht, es lagt wie sau.
Auch wenn die Seite reingeladen ist und aufgebaut ist es lagtt mit Mozilla,IExplorer,Maxthon!!!!!
Bitte nehmt eure Spinager,Trojnaer überwachung von der Steite runter, mann das merkt doch jeder warum das lagen tut, weill auf der Seite Programme arbeiten die geheim bleiben sollen !!!

Die Seiten von (siehe unten) gehen sau schnell !!!
https://msdn.microsoft.com
https://www.vbarchiv.net
https://www.youtube.com
ttps://books.google.de

MFG Grund Steffen

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 397627ee-64a9-0693-19ad-c14aee59cca2
* Version Independent ID: 1e561f21-e881-9500-872c-877069f3e8fd
* Content: [Dim-Anweisung (Visual Basic)](https://docs.microsoft.com/de-de/dotnet/visual-basic/language-reference/statements/dim-statement)
* Content Source: [docs/visual-basic/language-reference/statements/dim-statement.md](https://github.com/dotnet/docs.de-de/blob/live/docs/visual-basic/language-reference/statements/dim-statement.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hallo, @Knopfan, 

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
