### ISSUE TITLE
different output

### ISSUE THREAD

**Issue by lawgorht** [dotnet/docs.de-de#104]
Hi,

I've followed your tutorial 1:1 but I'm not getting the same correct output:

> 
> Warning: Format error at (83,3)-(83,4011): Illegal quoting
> Processed 251 rows with 0 bad values and 1 format errors
> Warning: Format error at (83,3)-(83,4011): Illegal quoting
> Processed 251 rows with 0 bad values and 1 format errors
> Not adding a normalizer.
> Making per-feature arrays
> Changing data from row-wise to column-wise
>  Bad value at line 1 in column Label
> Warning: Format error at (83,3)-(83,4011): Illegal quoting
> Processed 251 rows with 1 bad values and 1 format errors
> Processed 250 instances
> Binning and forming Feature objects
> Reserved memory for tree learner: 12771792 bytes
> Starting to train ...
> Not training a calibrator because it is not needed.
>   Bad value at line 1 in column Label
> Processed 19 rows with 1 bad values and 0 format errors
> 
> PredictionModel quality metrics evaluation
> 
> Accuracy: 94.44 %
> Auc: 98.77 %
> F1Score: 94.74 %
> 
> Sentiment Predictions
> 
> Sentiment: Please refrain from adding nonsense to Wikipedia. | Prediction: Positive
> Sentiment: He is the best, and the article should say that. | Prediction: Negative

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Verwenden von ML.NET in einem Standpunktanalyse-Szenario mit binärer Klassifizierung](https://docs.microsoft.com/de-de/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs.de-de/blob/live/docs/machine-learning/tutorials/sentiment-analysis.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @lawgorht,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
