### ISSUE TITLE
Operator Precedence table is not rendered as table

### ISSUE THREAD

**Issue by swsch** [dotnet/docs.de-de#115]
looks like some markdown has not been converted

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: eda0064b-feb6-ccf5-b77c-92e59be17b0c
* Version Independent ID: 7f789b6e-4f55-5740-2c2f-2dec4e2129fc
* Content: [Symbol- und Operatorenreferenz (F#)](https://docs.microsoft.com/de-de/dotnet/fsharp/language-reference/symbol-and-operator-reference/)
* Content Source: [docs/fsharp/language-reference/symbol-and-operator-reference/index.md](https://github.com/dotnet/docs.de-de/blob/live/docs/fsharp/language-reference/symbol-and-operator-reference/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
This is now fixed in master -> english (https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/#operator-precedence) so I suspect once another round of translation happens you'll see the updated table.

**Comment by swsch** [comment]
Thanks for fixing it so quickly.

I _was_ viewing the non-translated version (admittedly from the de-de page) and noticed only after posting that I still got sorted into de-de. Surprised me quite a bit :-)

**Comment by CeciAc** [comment]
Hi @swsch , 
Thanks for your comments.
I'm closing this issue since it was a problem with the source and will later be fixed in localized versions since this content is MT.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
