### ISSUE TITLE
Translation is not correct

### ISSUE THREAD

**Issue by JanO212** [dotnet/docs.de-de#116]
> Im folgenden Codebeispiel ist eine Anleitung zum Migrieren aus der veralteten xref:System.Xml.Schema.XmlSchemaSet-Klasse zur neuen xref:System.Xml.Schema.XmlSchemaCollection-Klasse enthalten.

In the english version the XmlSchemaCollection is the deprecated class. So the matching translation must be:

Im folgenden Codebeispiel ist eine Anleitung zum Migrieren aus der veralteten xref:System.Xml.Schema.XmlSchemaCollection-Klasse zur neuen xref:System.Xml.Schema.XmlSchemaSet-Klasse enthalten.

**Comment by CeciAc** [comment]
Hello, @JanO212 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order be able to address your feedback. 
**Can you please provide the URL?**
 
Kind regards,
Microsoft DOCS International Team

**Comment by JanO212** [comment]
Hello, @CeciAc 

I found it here: https://docs.microsoft.com/de-de/dotnet/standard/data/xml/xmlschemaset-for-schema-compilation
It is the first sentence in the part "Migration to "XmlSchemaSet"". I think that only the references are reversed.

Kind regrads,
Jan

**Comment by CeciAc** [comment]
Hello, @JanO212 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @JanO212 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/dotnet/standard/data/xml/xmlschemaset-for-schema-compilation. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
