### ISSUE TITLE
Beschreibungsfehler

### ISSUE THREAD

**Issue by Alexees** [dotnet/docs.de-de#117]
2. Die select-Anweisung gibt die Name-Eigenschaft statt des vollständigen Customer-Objekts zurück. Da Name eine Zeichenfolge ist, lautet das Typargument von custNameQuery nicht string, sondern Customer.

es muss heißen “nicht Customer, sondern string“

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 96adc2bd-5b01-8291-a386-486c9ee2bbb5
* Version Independent ID: 141dc0ca-40ed-dace-4d21-377ac99537b6
* Content: [Typbeziehungen in LINQ-Abfragevorgängen (C#)](https://docs.microsoft.com/de-de/dotnet/csharp/programming-guide/concepts/linq/type-relationships-in-linq-query-operations)
* Content Source: [docs/csharp/programming-guide/concepts/linq/type-relationships-in-linq-query-operations.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/programming-guide/concepts/linq/type-relationships-in-linq-query-operations.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hallo, @Alexees 

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @Alexees

Vielen Dank für Ihr Feedback.

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen.

Mit freundlichen Grüßen
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @Alexees 
 
Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/dotnet/csharp/programming-guide/concepts/linq/type-relationships-in-linq-query-operations
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
