### ISSUE TITLE
Parameters not documented

### ISSUE THREAD

**Issue by agowa338** [dotnet/docs.de-de#118]
Parameters are not documented (output of `dotnet msbuild /help`)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a9083568-6c58-1c1b-0062-10632e61a88d
* Version Independent ID: a1d47471-9482-9f69-f11e-3424e62383f6
* Content: [dotnet-msbuild-Befehl – .NET Core-CLI](https://docs.microsoft.com/de-de/dotnet/core/tools/dotnet-msbuild)
* Content Source: [docs/core/tools/dotnet-msbuild.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/tools/dotnet-msbuild.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #9794](https://github.com/dotnet/docs/issues/9794) via [**ZenHub**](https://www.zenhub.com/)
