### ISSUE TITLE
Microservices Communication

### ISSUE THREAD

**Issue by harry12345678910** [dotnet/docs.de-de#128]
Dear all,
I am struggling a little bit with the approach to "if your initial microservice needs data that's originally owned by other microservices, do not rely on making synchronous requests for that data. Instead, replicate or propagate that data (only the attributes you need) into the initial service's database". 
E.g. I have an ordering service where orders can be placed. The ordering service has to check whether a customer is allowed to purchase a certain product (e.g. pharmaceutical). This would mean that this special customer data needs to be synchronized to the ordering database. Additionally a response from "createOrder" should be the expected delivery time slot. Therefor the availability/stocklevels need to be checked which is usually part of an inventory/warehouse service. Should the stocklevels than also being synced to the order service? Doesn't this create a way to big service? What about SPOR?
Thanks for your help.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 89fd8427-589c-9158-f9e9-6b59d34ac4e2
* Version Independent ID: 3091e297-8939-cc0c-7437-5ec8be56ae3c
* Content: [Kommunikation in einer Microservicearchitektur](https://docs.microsoft.com/de-de/dotnet/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture#feedback)
* Content Source: [docs/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture.md](https://github.com/dotnet/docs.de-de/blob/live/docs/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @harry12345678910 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
