### ISSUE TITLE
SyntaxError when executing code sample

### ISSUE THREAD

**Issue by MSeifert04** [dotnet/docs.de-de#129]
In  docs.de-de/docs/standard/base-types/standard-numeric-format-strings.md 

![Unbenannt](https://user-images.githubusercontent.com/14200878/54689268-7a557100-4b1f-11e9-8b50-5c849006cc02.png)

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11413](https://github.com/dotnet/docs/issues/11413) via [**ZenHub**](https://www.zenhub.com/)

**Comment by MSeifert04** [comment]
Thanks for moving the issue. I did not realize the examples are in a different Repo.
