### ISSUE TITLE
Warning is not properly formatted

### ISSUE THREAD

**Issue by Angr1st** [dotnet/docs.de-de#131]
![fsharpdocsProperties](https://user-images.githubusercontent.com/18403581/55263019-05491080-5270-11e9-9210-6296a0e2d43a.PNG)
The Warning block is not properly formatted

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1092e481-8bd1-27c6-1da6-4e82db4028c4
* Version Independent ID: 3a70e9e1-c517-6366-c82e-8a23e89e0cec
* Content: [Eigenschaften](https://docs.microsoft.com/de-de/dotnet/fsharp/language-reference/members/properties)
* Content Source: [docs/fsharp/language-reference/members/properties.md](https://github.com/dotnet/docs.de-de/blob/live/docs/fsharp/language-reference/members/properties.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by CeciAc** [comment]
Hello @Angr1st 

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/dotnet/fsharp/language-reference/members/properties 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
