### ISSUE TITLE
The warning block formatting is off

### ISSUE THREAD

**Issue by Angr1st** [dotnet/docs.de-de#133]
![fsharpdocsdeval](https://user-images.githubusercontent.com/18403581/55264491-d8e3c300-5274-11e9-8c83-d036e091f6ee.PNG)
The warning block is incorrectly formatted. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4e2e5224-d14f-01ef-37ea-7ebc83e31381
* Version Independent ID: 75f5241f-5677-094e-a80a-4cbc8aa533df
* Content: [Explizite Felder: Das Val Schlüsselwort](https://docs.microsoft.com/de-de/dotnet/fsharp/language-reference/members/explicit-fields-the-val-keyword)
* Content Source: [docs/fsharp/language-reference/members/explicit-fields-the-val-keyword.md](https://github.com/dotnet/docs.de-de/blob/live/docs/fsharp/language-reference/members/explicit-fields-the-val-keyword.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by CeciAc** [comment]
Hello @Angr1st 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/dotnet/fsharp/language-reference/members/explicit-fields-the-val-keyword

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
