### ISSUE TITLE
Provide example without using DataSet/DataRelation classes and utilizing an object graph instead

### ISSUE THREAD

**Issue by rschindhelm-haba** [dotnet/docs.de-de#136]
It would be great to see an example without the help of the DataSet and DataRelation classes and directed more towards a graph of business objects and their relations.

Make it clear that binding is only possible for properties directly owned by the object-to-be-bound and not for any of its contained objects' properties. Show a way of how to circumvent those restrictions.

Thank you.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0f0f9f77-8ccd-3c8a-03db-cdc2bfcbf0dd
* Version Independent ID: b198318d-0b9f-920e-a8a3-1d95f98e8eae
* Content: [Vorgehensweise: Erstellen Sie ein Master / Detail-Formular mit zwei DataGridView-Steuerelementen in Windows Forms](https://docs.microsoft.com/de-de/dotnet/framework/winforms/controls/create-a-master-detail-form-using-two-datagridviews)
* Content Source: [docs/framework/winforms/controls/create-a-master-detail-form-using-two-datagridviews.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/winforms/controls/create-a-master-detail-form-using-two-datagridviews.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11789](https://github.com/dotnet/docs/issues/11789) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @rschindhelm-haba 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/11789

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
