### ISSUE TITLE
operator "like" is supported by VB

### ISSUE THREAD

**Issue by UlliBien** [dotnet/docs.de-de#137]
documentation is wrong. operator "like" is supported by VB. you can overwrite it too.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bec570c0-3c04-a8d1-9f13-1696f93080a3
* Version Independent ID: ce60c1cc-649a-5bef-28b2-ac34108d9483
* Content: [Like-Operator (Visual Basic)](https://docs.microsoft.com/de-de/dotnet/visual-basic/language-reference/operators/like-operator?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(vb.Like)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%3Bk(DevLang-VB)%26rd%3Dtrue#feedback)
* Content Source: [docs/visual-basic/language-reference/operators/like-operator.md](https://github.com/dotnet/docs.de-de/blob/live/docs/visual-basic/language-reference/operators/like-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11845](https://github.com/dotnet/docs/issues/11845) via [**ZenHub**](https://www.zenhub.com/)
