### ISSUE TITLE
Typo in NuGet Package

### ISSUE THREAD

**Issue by franzgram** [dotnet/docs.de-de#139]
Falsch: Microsoft.MLT.ensorFlow 0.10.0 NuGet-Paket
Korrrekt: Microsoft.ML.TensorFlow 0.10.0 NuGet-Paket

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Erstellen einer benutzerdefinierten ML.NET-Bildklassifizierung mit TensorFlow](https://docs.microsoft.com/de-de/dotnet/machine-learning/tutorials/image-classification#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs.de-de/blob/live/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Hallo, @franzgram 

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @franzgram 
  
Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/dotnet/machine-learning/tutorials/image-classification#feedback
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
