### ISSUE TITLE
Resources of Arrows

### ISSUE THREAD

**Issue by Prodigio** [dotnet/docs.de-de#141]
Is there a way to get the default Windows styled arrows to download somewhere?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2e47e2cf-6ecf-32c8-ee13-81af9711260c
* Version Independent ID: 09e85a4a-d6a6-7f11-0cea-5ffd3e9cea1c
* Content: [Vorgehensweise: Sortieren einer GridView-Spalte beim Klicken auf einen Header](https://docs.microsoft.com/de-de/dotnet/framework/wpf/controls/how-to-sort-a-gridview-column-when-a-header-is-clicked#feedback)
* Content Source: [docs/framework/wpf/controls/how-to-sort-a-gridview-column-when-a-header-is-clicked.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/wpf/controls/how-to-sort-a-gridview-column-when-a-header-is-clicked.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @Prodigio 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
