### ISSUE TITLE
Can't find trainer

### ISSUE THREAD

**Issue by Neralem** [dotnet/docs.de-de#142]
The Namespace Microsoft.ML.Trainers.FastTree does not exist for me. Microsoft.ML.Trainers does. Do i miss something?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Vorhersagen von Preisen per Regression - ML.NET](https://docs.microsoft.com/de-de/dotnet/machine-learning/tutorials/predict-prices#feedback)
* Content Source: [docs/machine-learning/tutorials/predict-prices.md](https://github.com/dotnet/docs.de-de/blob/live/docs/machine-learning/tutorials/predict-prices.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by Neralem** [comment]
Edit: I'm using Visual Studio Professional 2019 Version 16.1.3 and installed Microsoft.ML v1.1.0 via NuGet. I've also installed the Crossplatform .Net Core-Development Kit and everything is up to date.

**Comment by Neralem** [comment]
Nervermind. Seems that i have to install another NuGet package for this. Microsoft.ML.FastTree has it.

**Comment by CeciAc** [comment]
Hello, @Neralem 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
