### ISSUE TITLE
The link to the code example is dead

### ISSUE THREAD

**Issue by joh397** [dotnet/docs.de-de#144]
The link to the example code (https://go.microsoft.com/fwlink/?LinkID=159996) is dead.
The link can be found in the last sentence of the first paragraph.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a377bf0b-fc73-2df8-e2b8-a8d1e0f688fb
* Version Independent ID: 7fc5b667-3df0-8d10-93fe-294218fc5135
* Content: [Exemplarische Vorgehensweise: Hosten eines zusammengesetzten WPF-Steuerelements in Windows Forms](https://docs.microsoft.com/de-de/dotnet/framework/wpf/advanced/walkthrough-hosting-a-wpf-composite-control-in-windows-forms#feedback)
* Content Source: [docs/framework/wpf/advanced/walkthrough-hosting-a-wpf-composite-control-in-windows-forms.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/wpf/advanced/walkthrough-hosting-a-wpf-composite-control-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @joh397
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #13510](https://github.com/dotnet/docs/issues/13510) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @joh397

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/13510

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
