### ISSUE TITLE
katastrophale deutsche Übersetzung der "Collections"

### ISSUE THREAD

**Issue by TerranUlm** [dotnet/docs.de-de#150]
Der Artikel ist auf deutsch praktisch nicht zu verstehen.  Verwendet man dagegen einen beliebigen Online-Translator (Bing, Google, DeepL), dann wird das englisch tadellos ins deutsche übersetzt.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 18eeec0c-2b8e-437a-9da6-0fb3517da8f5
* Version Independent ID: a6a57a0c-50c0-d899-3121-f61fc1482fa7
* Content: [Arrays in Visual Basic](https://docs.microsoft.com/de-de/dotnet/visual-basic/programming-guide/language-features/arrays/#feedback)
* Content Source: [docs/visual-basic/programming-guide/language-features/arrays/index.md](https://github.com/dotnet/docs.de-de/blob/live/docs/visual-basic/programming-guide/language-features/arrays/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @TerranUlm
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @TerranUlm 

Vielen Dank für Ihr Feedback. Die betroffene Seite wurde maschinenübersetzt. Daher kann es sein, dass der Inhalt nicht immer verständlich ist. Wir haben vor Kurzem die Option „Read in English“ (Auf Englisch lesen) rechts hinzugefügt, sodass Sie zur englischen Version wechseln können, ohne die Spracheinstellungen ändern zu müssen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
