### ISSUE TITLE
Domain Entities as POCO's or with Data and Behaviour

### ISSUE THREAD

**Issue by guenschn** [dotnet/docs.de-de#159]
The discussion in my team reflects the contradiction above -  both approaches to domain entities are recommended above. We consider to implement business logic in a domain root object - which might be an object reflected in the repository (like an "Order" in an order management microservice), but not necessarily so. With this approach we would implement a command like this: 
(1) Construct the Aggregate root object from objects fetched from the database (which might be EF-POCOs)
(2) Call one or more business logic methods on the root object which will modify the aggregate (the EF-POCOs)
(3) Reflect back into the EF entities (if necessary) and invoke repository.savechanges (a method which calls EF's savechanges and perhaps does some logging, audit trail writing etc.) to get transactional behaviour for the command. 
We would like to avoid repository calls from business logic methods - that would have to be handled during Phase (1). However, that looks a bit like having part of the Business logic in Phase (1) and part in Phase (2). Advice welcome by a DDD newcomer.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 95f3dcd7-3220-e9cf-3ca6-90b1282410ec
* Version Independent ID: 5a30bea5-326b-ea72-59ae-dfef1e190e4a
* Content: [Entwerfen eines DDD-orientierten Microservices](https://docs.microsoft.com/de-de/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md](https://github.com/dotnet/docs.de-de/blob/live/docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @guenschn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @guenschn 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
