### ISSUE TITLE
Windows-Dialogfeld Programme hinzufügen/entfernen zeigt nicht alle installierten Versionen an

### ISSUE THREAD

**Issue by mshobohm** [dotnet/docs.de-de#160]
Mit dotnet --list-sdks bekomme ich einige alte SDKs angezeigt die ich im "Windows-Dialogfeld Programme hinzufügen/entfernen" nicht angezeigt bekomme. Folglich lassen sich diese wohl nur per Löschen im Explorer deinstallieren, ich hoffe das das rückstandsfrei ist. Die Seite könnte was zu diesem Thema schreiben.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [Entfernen von .NET Core Runtime und SDK - .NET Core](https://docs.microsoft.com/de-de/dotnet/core/versions/remove-runtime-sdk-versions?tabs=windows#uninstalling-net-core)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @mshobohm
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #15865](https://github.com/dotnet/docs/issues/15865) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hallo, @mshobohm  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/dotnet/docs/issues/15865
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
