### ISSUE TITLE
Date format for month is not correct

### ISSUE THREAD

**Issue by xp-development** [dotnet/docs.de-de#164]
The format string for a month of a DateTime is incorrect if the specifier stands alone. 

Console.WriteLine(DateTime.Now.ToString("M"));
// Actual: "13. Januar"
// Expected: "1"

If the format specifier longer than one character it works like expected. 
Console.WriteLine(DateTime.Now.ToString("M "));
// "1 "

**Comment by srvbpigh** [comment]
Hello, @xp-development
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by xp-development** [comment]
Sorry. Now I read to the end of the documentation and I saw that this behavior is desired.

[Doc](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#notes)

**Comment by CeciAc** [comment]
Hello, @xp-development 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
