### ISSUE TITLE
Raspbian fresh install sudo apt-get install dotnet-runtime-3.1 not working

### ISSUE THREAD

**Issue by zebrassimo** [dotnet/docs.de-de#167]
While following the instructions,, I'll still get the error that packet dotnet-runtinme-3.1 couldn't be found:

login as: pi
pi@192.168.2.122's password:
Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Mar 11 20:47:17 2020
pi@raspberrypi:~ $  passwd
Ändern des Passworts für pi.
Current password:
Geben Sie ein neues Passwort ein:
Geben Sie das neue Passwort erneut ein:
Passwort nicht geändert
Geben Sie ein neues Passwort ein:
Geben Sie das neue Passwort erneut ein:
Kein Passwort angegeben
Geben Sie ein neues Passwort ein:
Geben Sie das neue Passwort erneut ein:
Die Passwörter stimmen nicht überein.
passwd: Fehler beim Ändern des Authentifizierungstoken
passwd: Passwort nicht geändert
pi@raspberrypi:~ $ sudo passwd root
Geben Sie ein neues Passwort ein:
Geben Sie das neue Passwort erneut ein:
passwd: Passwort erfolgreich geändert
pi@raspberrypi:~ $ wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
pi@raspberrypi:~ $ sudo dpkg -i packages-microsoft-prod.deb
Vormals nicht ausgewähltes Paket packages-microsoft-prod wird gewählt.
(Lese Datenbank ... 93561 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von packages-microsoft-prod.deb ...
Entpacken von packages-microsoft-prod (1.0-ubuntu19.04.1) ...
packages-microsoft-prod (1.0-ubuntu19.04.1) wird eingerichtet ...
pi@raspberrypi:~ $ sudo apt-get update
Holen:1 https://packages.microsoft.com/ubuntu/19.04/prod disco InRelease [3.996 B]
OK:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
OK:3 http://archive.raspberrypi.org/debian buster InRelease
Holen:4 https://packages.microsoft.com/ubuntu/19.04/prod disco/main amd64 Packages [28,8 kB]
Es wurden 32,8 kB in 1 s geholt (31,4 kB/s).
Paketlisten werden gelesen... Fertig
pi@raspberrypi:~ $ sudo apt-get install apt-transport-https
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  apt-transport-https
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 149 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 156 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf apt-transport-https all 1.8.2 [149 kB]
Es wurden 149 kB in 0 s geholt (426 kB/s).
Vormals nicht ausgewähltes Paket apt-transport-https wird gewählt.
(Lese Datenbank ... 93569 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../apt-transport-https_1.8.2_all.deb ...
Entpacken von apt-transport-https (1.8.2) ...
apt-transport-https (1.8.2) wird eingerichtet ...
pi@raspberrypi:~ $ sudo apt-get update
OK:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
OK:2 http://archive.raspberrypi.org/debian buster InRelease
OK:3 https://packages.microsoft.com/ubuntu/19.04/prod disco InRelease
Paketlisten werden gelesen... Fertig
pi@raspberrypi:~ $ sudo apt-get install dotnet-sdk-3.1
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket dotnet-sdk-3.1 kann nicht gefunden werden.
E: Mittels des Musters »dotnet-sdk-3.1« konnte kein Paket gefunden werden.
E: Mittels regulärem Ausdruck »dotnet-sdk-3.1« konnte kein Paket gefunden werden.
pi@raspberrypi:~ $ sudo dpkg --purge packages-microsoft-prod && sudo dpkg -i packages-microsoft-prod.deb
(Lese Datenbank ... 93573 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von packages-microsoft-prod (1.0-ubuntu19.04.1) ...
Löschen der Konfigurationsdateien von packages-microsoft-prod (1.0-ubuntu19.04.1) ...
Vormals nicht ausgewähltes Paket packages-microsoft-prod wird gewählt.
(Lese Datenbank ... 93565 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von packages-microsoft-prod.deb ...
Entpacken von packages-microsoft-prod (1.0-ubuntu19.04.1) ...
packages-microsoft-prod (1.0-ubuntu19.04.1) wird eingerichtet ...
pi@raspberrypi:~ $ sudo apt-get update
OK:1 http://archive.raspberrypi.org/debian buster InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
OK:3 https://packages.microsoft.com/ubuntu/19.04/prod disco InRelease
Paketlisten werden gelesen... Fertig
pi@raspberrypi:~ $ sudo apt-get install dotnet-sdk-3.1
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket dotnet-sdk-3.1 kann nicht gefunden werden.
E: Mittels des Musters »dotnet-sdk-3.1« konnte kein Paket gefunden werden.
E: Mittels regulärem Ausdruck »dotnet-sdk-3.1« konnte kein Paket gefunden werden.
pi@raspberrypi:~ $ sudo apt-get install -y gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/ubuntu/19.04/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get install -y apt-transport-https
sudo apt-get update
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
gpg ist schon die neueste Version (2.2.12-1+rpi1+deb10u1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
pi@raspberrypi:~ $ wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o microsoft.asc.gpg
pi@raspberrypi:~ $ sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
pi@raspberrypi:~ $ wget -q https://packages.microsoft.com/config/ubuntu/19.04/prod.list
pi@raspberrypi:~ $ sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
pi@raspberrypi:~ $ sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
pi@raspberrypi:~ $ sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
pi@raspberrypi:~ $ sudo apt-get install -y apt-transport-https
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
apt-transport-https ist schon die neueste Version (1.8.2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
pi@raspberrypi:~ $ sudo apt-get update
OK:1 http://archive.raspberrypi.org/debian buster InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
OK:3 https://packages.microsoft.com/ubuntu/19.04/prod disco InRelease
Paketlisten werden gelesen... Fertig
pi@raspberrypi:~ $ sudo apt-get install dtonet-sdk-3.1
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket dtonet-sdk-3.1 kann nicht gefunden werden.
E: Mittels des Musters »dtonet-sdk-3.1« konnte kein Paket gefunden werden.
E: Mittels regulärem Ausdruck »dtonet-sdk-3.1« konnte kein Paket gefunden werden.
pi@raspberrypi:~ $ sudo apt-get update
OK:1 https://packages.microsoft.com/ubuntu/19.04/prod disco InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
OK:3 http://archive.raspberrypi.org/debian buster InRelease
Paketlisten werden gelesen... Fertig
pi@raspberrypi:~ $ sudo apt-get install apt-transport-https
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
apt-transport-https ist schon die neueste Version (1.8.2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
pi@raspberrypi:~ $ sudo apt-get update
OK:1 http://archive.raspberrypi.org/debian buster InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
OK:3 https://packages.microsoft.com/ubuntu/19.04/prod disco InRelease
Paketlisten werden gelesen... Fertig
pi@raspberrypi:~ $ sudo apt-get install dotnet-runtime-3.1
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket dotnet-runtime-3.1 kann nicht gefunden werden.
E: Mittels des Musters »dotnet-runtime-3.1« konnte kein Paket gefunden werden.
E: Mittels regulärem Ausdruck »dotnet-runtime-3.1« konnte kein Paket gefunden werden.
pi@raspberrypi:~ $

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 172f0b88-61f2-d631-478f-e88af9be1f7d
* Version Independent ID: c610685f-57a2-048d-8dfa-146e19943434
* Content: [Installieren von .NET Core auf Ubuntu 19.04 mit einem Paket-Manager (.NET Core)](https://docs.microsoft.com/de-de/dotnet/core/install/linux-package-manager-ubuntu-1904)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1904.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/install/linux-package-manager-ubuntu-1904.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @zebrassimo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by zebrassimo** [comment]
I've got it working using the manual install. The issue was that I didn't look for the ARM install. The scripts would default to the X64 install.
