### ISSUE TITLE
libicu not found when using zypper

### ISSUE THREAD

**Issue by SchoolGuy** [dotnet/docs.de-de#168]
Currently the command `sudo zypper install libicu` will not work because suse uses a different naming schema for this. Since I don't know what exact package is needed for .NET/.NET Core here is the link to the OBS Repository where all packages are built: https://build.opensuse.org/package/show/openSUSE%3AFactory/icu

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b6baea63-f650-e232-854b-c1722ed72543
* Version Independent ID: 56c0bff6-2630-06f8-9c86-e81ca292fd2f
* Content: [Installieren von .NET Core auf openSUSE 15 mit einem Paket-Manager (.NET Core)](https://docs.microsoft.com/de-de/dotnet/core/install/linux-package-manager-opensuse15#feedback)
* Content Source: [docs/core/install/linux-package-manager-opensuse15.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/install/linux-package-manager-opensuse15.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @SchoolGuy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #17470](https://github.com/dotnet/docs/issues/17470) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @SchoolGuy, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/17470. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
