### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by milbrandt** [dotnet/docs.de-de#170]
- _Zeichenfolgen_ ist ein Wort
- _Zeichen folgen mit drei Zeichen_ sollte  eher _Zeichenfolgen mit dreifachen Anführungszeichen_

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 752405db-4da8-6c06-f58b-22dcc9caa7a7
* Version Independent ID: 78362807-847f-b947-2c75-5036f7765b32
* Content: [Zeichenfolgen - F#](https://docs.microsoft.com/de-de/dotnet/fsharp/language-reference/strings#triple-quoted-strings)
* Content Source: [docs/fsharp/language-reference/strings.md](https://github.com/dotnet/docs.de-de/blob/live/docs/fsharp/language-reference/strings.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @milbrandt
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo @milbrandt 

Vielen Dank für Ihren Beitrag.

Beiträge zu Übersetzungsproblemen in maschinell übersetzten Inhalten werden zurzeit nicht akzeptiert.

Wir schätzen Ihr Feedback und Ihre Vorschläge zu von Menschen übersetzten Inhalten. Diese werden verwendet, um die Engines für maschinelle Übersetzung zu trainieren. Mit der Zeit verbessern Ihre Beiträge also die Qualität menschlicher und maschineller Übersetzungen.

Anhand des ms.translationtype-Metadatenwerts im Header einer Inhaltsdatei können Sie zwischen menschlicher und maschineller Übersetzung unterscheiden. Dabei steht „HT“ für menschliche Übersetzung und „MT“ für maschinelle Übersetzung.

Vielen Dank für Ihre Unterstützung!

Microsoft DOCS Global Experience Team
