### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fmillerr** [dotnet/docs.de-de#171]
In den "Verwandte Abschnitte" ist ein Link Namens: "Reflexion". Die Seite führt aber zu Reflektion.
Reflexion != Reflektion

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c8bc41f1-c2f4-3d82-d65b-e986735162bd
* Version Independent ID: 1b8ea375-81a3-caef-f51a-f08635c6610a
* Content: [Reflektion (C#)](https://docs.microsoft.com/de-de/dotnet/csharp/programming-guide/concepts/reflection#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/reflection.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/programming-guide/concepts/reflection.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @fmillerr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @fmillerr 

Vielen Dank für Ihr Feedback.

unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/dotnet/csharp/programming-guide/concepts/reflection#feedback

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.

Mit freundlichen Grüßen

das Microsoft DOCS International Team
