### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by Baozi-face** [dotnet/docs.de-de#172]
hello 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 67b4c020-d187-0c5c-1459-b64babf8bf87
* Version Independent ID: 3b04f784-4571-6728-b892-5b0c090c32ff
* Content: [循环结构 - Visual Basic](https://docs.microsoft.com/zh-cn/dotnet/visual-basic/programming-guide/language-features/control-flow/loop-structures)
* Content Source: [docs/visual-basic/programming-guide/language-features/control-flow/loop-structures.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/visual-basic/programming-guide/language-features/control-flow/loop-structures.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @Baozi-face
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Feedback is empty
