### ISSUE TITLE
NET Core 指南 404 - 找不到页面

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/docs.de-de#173]
点击 NET Core 指南 https://docs.microsoft.com/zh-cn/dotnet/core/index.md
显示 NET Core 指南 404 - 找不到页面。

请检查。谢谢。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0ba03a7c-8cbe-7670-c2e9-9b692556361c
* Version Independent ID: d085d268-bff6-f355-80b4-01c1023a5914
* Content: [.NET 体系结构组件](https://docs.microsoft.com/zh-cn/dotnet/standard/components#feedback)
* Content Source: [docs/standard/components.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/components.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @cartermp
* Microsoft Alias: **gewarren**

**Comment by kinglionsz** [comment]
<img width="635" alt="NET Core 指南404" src="https://user-images.githubusercontent.com/51827261/78101070-e946f480-7418-11ea-860d-f72dd3b1b69e.png">

**Comment by srvbpigh** [comment]
Hello, @kinglionsz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
感谢你的反馈。  


我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/standard/components#feedback


非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  


深深的祝福，  

Microsoft DOCS International Team
