### ISSUE TITLE
Botões trocados

### ISSUE THREAD

**Issue by yzk23** [dotnet/docs.de-de#174]
Clicar no botão próximo está voltando a página.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 0ba2da58-10b2-ac3d-83ea-df35ebe776dc
* Version Independent ID: eec71f65-f787-abdf-23fc-5ab25a3ab27e
* Content: [Introdução aos contêineres e ao Docker](https://docs.microsoft.com/pt-br/dotnet/architecture/microservices/container-docker-introduction/#feedback)
* Content Source: [docs/architecture/microservices/container-docker-introduction/index.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/architecture/microservices/container-docker-introduction/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @yzk23
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Vielen Dank für Ihr Feedback.  

Unsere Technikexperten haben sich Ihre Vorschläge angesehen und für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/pt-br/dotnet/architecture/microservices/container-docker-introduction/#feedback.   

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.  

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
