### ISSUE TITLE
Prima Beschreibung

### ISSUE THREAD

**Issue by daple** [dotnet/docs.de-de#176]
Konnte man gut nachvollziehen, danke! Im Part "Verarbeiten des JSON-Ergebnisses" fehlt evtl. der explizite Hinweis darauf, dass man 'using System.Collections.Generic;' einfügen sollte, aber das geht ja aus dem Text hervor.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Erstellen eines REST-Clients mithilfe von .NET Core](https://docs.microsoft.com/de-de/dotnet/csharp/tutorials/console-webapiclient#feedback)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @daple
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @daple 

vielen Dank für Ihr Feedback. Es freut uns, dass Sie mir unserer Dokumentation zufrieden sind.

Sie können gerne weiterhin Feedback abgeben, damit wir die Servicequalität kontinuierlich verbessern können.


Mit freundlichen Grüßen

das Microsoft DOCS International Team
