### ISSUE TITLE
文件：dotnet-install 指令碼參考，內文修正需求

### ISSUE THREAD

**Issue by wujpkimo** [dotnet/docs.de-de#180]
[請在此輸入您的意見]

文章連結：https://docs.microsoft.com/zh-tw/dotnet/core/tools/dotnet-install-script#feedback

其中下列文字的第3行，建議修改，原文中的"電源外殼（視窗）"不應翻譯
我們建議您使用腳本的穩定版本：
Bash（Linux/macOS）：https://dot.net/v1/dotnet-install.sh
**電源外殼（視窗）：https://dot.net/v1/dotnet-install.ps1**
這行建議修改成 **PowerShell（Windows）：https://dot.net/v1/dotnet-install.ps1**

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install 指令碼 - .NET Core CLI](https://docs.microsoft.com/zh-tw/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @wujpkimo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@JasonCard This is a zh-tw issue, but for some reason it was automatically placed by mistake in the de-de repo. 
I'm moving this to the zh-tw repo to work on it, but I needed to report this bug.
best

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs.zh-tw #277](https://github.com/dotnet/docs.zh-tw/issues/277) via [**ZenHub**](https://www.zenhub.com/)
