### ISSUE TITLE
Italian traslation major error

### ISSUE THREAD

**Issue by DomizianoAtticciati** [dotnet/docs.de-de#183]
[Immetti qui i commenti]
In the italian traslation in the first line says "restituisce il valore dell'operando a sinistra se è null;"
Actually is the opposite :P.
It should be "restituisce il valore dell'operando a sinistra se NON è null;"

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 038ae35e-c5e9-e1a4-a6dd-afe379201245
* Version Independent ID: d73f3d5a-00d4-2e22-c120-8e8d6d101a54
* Content: [?? E?? Operatori - Riferimenti per C](https://docs.microsoft.com/it-it/dotnet/csharp/language-reference/operators/null-coalescing-operator#feedback)
* Content Source: [docs/csharp/language-reference/operators/null-coalescing-operator.md](https://github.com/dotnet/docs.it-it/blob/live/docs/csharp/language-reference/operators/null-coalescing-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @DomizianoAtticciati
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs.it-it #78](https://github.com/dotnet/docs.it-it/issues/78) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
moved to the it-it repo
