### ISSUE TITLE
Matriz [10] contém 11 elementos ao invés de 10 como foi dito na explicação acima

### ISSUE THREAD

**Issue by NiceShot** [dotnet/docs.de-de#184]
Na verdade uma array armazena na memória desde o [0]. No exemplo acima a array com o valor de [10] reserva na memória 11 elementos.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 64f269de-137f-a763-a4e2-f2f5b1ce9dd3
* Version Independent ID: ad83c8b9-a95a-e336-ff31-52fb1fdb4b14
* Content: [Matrizes em C# - um tour pela linguagem C#](https://docs.microsoft.com/pt-br/dotnet/csharp/tour-of-csharp/arrays#feedback)
* Content Source: [docs/csharp/tour-of-csharp/arrays.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/tour-of-csharp/arrays.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @NiceShot
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #17793](https://github.com/dotnet/docs/issues/17793) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
@JasonCard please check this issue, it comes from a pt-br page but creates the issue in the de-de repo
