### ISSUE TITLE
Exemple ne fonctionne pas

### ISSUE THREAD

**Issue by yannpelissier** [dotnet/docs.de-de#185]
Bonjour et merci pour vos exemples et votre documentation souvent de qualité.
Mais votre exemple ne fonctionne pas chez moi : fullTrustAssembly est null et provoque une erreur lors de la création du domaine.

VS2019, framework 4.8, C# 8.0

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 0505d926-b70e-94df-d4ef-1d70737d0353
* Version Independent ID: 1bf0791b-8627-9113-a0b3-e52987bd4d59
* Content: [Comment : exécuter du code d'un niveau de confiance partiel dans un bac à sable (sandbox)](https://docs.microsoft.com/fr-fr/dotnet/framework/misc/how-to-run-partially-trusted-code-in-a-sandbox#feedback)
* Content Source: [docs/framework/misc/how-to-run-partially-trusted-code-in-a-sandbox.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/framework/misc/how-to-run-partially-trusted-code-in-a-sandbox.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by srvbpigh** [comment]
Hello, @yannpelissier
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by yannpelissier** [comment]
Erreur de ma part, je n'avait pas créé le projet UntrustedCode !!!

Désolé pour le dérangement.

**Comment by yannpelissier** [comment]
fullTrustAssembly is always null but without it it's OK.
