### ISSUE TITLE
Parfait

### ISSUE THREAD

**Issue by claudelarocque** [dotnet/docs.de-de#186]
Il faut faire des tests pour comprendre, mais ça vaut la peine de bien maîtriser les nombres et les types de nombres.

Claude

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: fb6905a9-e9ec-df6f-5733-dfb25a41b97a
* Version Independent ID: fe0e2716-651b-a883-6371-ded1ace94a11
* Content: [Nombres en C# – Tutoriel d’introduction à C#](https://docs.microsoft.com/fr-ca/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @claudelarocque
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @claudelarocque 

Merci pour votre feedback. Nous sommes heureux d’apprendre que notre documentation répond à vos attentes.  

Dans une optique d’amélioration constante, nous vous encourageons à envoyer vos commentaires à Microsoft.  

Cordialement,

L’équipe Microsoft DOCS International
