### ISSUE TITLE
I know why it was called ChallengeAnswer

### ISSUE THREAD

**Issue by claudelarocque** [dotnet/docs.de-de#187]
Almost everything was straight forward except for the ChallengeAnswer, I didn't get the following: 
The operator % gives you the rest of a division operation, after testing it seems to means that gives me all the numbers that are divisible by 3 and add them all. So to confirm I did divisible by 5 up to 50 and my answer before the test was 275....testing
and sure enough the response was: The sum is 275
Thanks it was very interesting this page

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: f1138d70-1d83-a7e5-8549-72bf80dc5834
* Version Independent ID: 0811beda-ff7e-353a-aeb2-6bebe8947bcf
* Content: [Branches et boucles – Tutoriel d’introduction à C#](https://docs.microsoft.com/fr-ca/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops-local)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops-local.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/csharp/tutorials/intro-to-csharp/branches-and-loops-local.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @claudelarocque
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @claudelarocque 
Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations. 
We encourage you to provide your valuable feedback so that we can continue improve your experience. 

Kind regards, 

Microsoft DOCS International Team
