### ISSUE TITLE
日本語の修正

### ISSUE THREAD

**Issue by hmoriya** [dotnet/docs.de-de#188]
Referancesｍにあるリンク名ですが、佐賀ではなくサーガ、あるいはサガパターン。佐賀は地名です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6fe83aa0-27b7-3270-4f5c-64f7797595b2
* Version Independent ID: 48bc49f8-e895-9fd4-a0d7-e3a8f519bbe6
* Content: [クラウドネイティブアプリケーションでのエラスティックサーチ](https://docs.microsoft.com/ja-jp/dotnet/architecture/cloud-native/elastic-search-in-azure#feedback)
* Content Source: [docs/architecture/cloud-native/elastic-search-in-azure.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/architecture/cloud-native/elastic-search-in-azure.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @hmoriya
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@hmoriya  様:  

投稿いただき、ありがとうございます。 

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。 

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。 

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。 


サポートいただきありがとうございます。 

Microsoft DOCS グローバル エクスペリエンス チーム

**Comment by CeciAc** [comment]
@JasonCard Japanese issue wrongly redirected to de-de repo

**Comment by hmoriya** [comment]
I understand that the machine translation cannot be corrected.Thanks
