### ISSUE TITLE
Overtranslated text in Spanish version

### ISSUE THREAD

**Issue by AlbertoPoblacion** [dotnet/docs.de-de#190]
The text translates "Data Source" under "Palabras clave" (keywords) as "Origen de Datos". This should not be translated: it is a keyword in the connection string where it should be always specified in English or you will get an error when opening the connection.

Also, this "Issues" entry appears to be under docs.de-de, but it was reached by clicking on the github link in the es-es documentation page. This would indicate some kind of issue with the hyperlink embedded in the page.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 054ee24a-82e4-7bb5-fff5-bb1ab5713472
* Version Independent ID: 8eec3e85-0630-15db-ff40-c89920b89526
* Content: [Cadenas de conexión - Microsoft.Data.Sqlite](https://docs.microsoft.com/es-es/dotnet/standard/data/sqlite/connection-strings?source=docs)
* Content Source: [docs/standard/data/sqlite/connection-strings.md](https://github.com/dotnet/docs.es-es/blob/live/docs/standard/data/sqlite/connection-strings.md)
* Product: **dotnet**
* Technology: **dotnet-data**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by srvbpigh** [comment]
Hello, @AlbertoPoblacion
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @AlbertoPoblacion

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
