### ISSUE TITLE
Float'tan int'e dönüşüm yaparken yanlış yapıyor.

### ISSUE THREAD

**Issue by XLIVE99** [dotnet/docs.de-de#191]
(int)(2.02f * 100) sonucunu 201 döndürüyor ancak (int)(2.02001f * 100) sonucunu 202 döndürüyor.

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 91266ab9-071d-067c-df52-8a297045af24
* Version Independent ID: 1d378928-4bb5-6bcf-49ca-2026768ab2aa
* Content: [Döküm ve tür dönüşümleri - C# Programlama Kılavuzu](https://docs.microsoft.com/tr-tr/dotnet/csharp/programming-guide/types/casting-and-type-conversions#feedback)
* Content Source: [docs/csharp/programming-guide/types/casting-and-type-conversions.md](https://github.com/dotnet/docs.tr-tr/blob/live/docs/csharp/programming-guide/types/casting-and-type-conversions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @XLIVE99
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs.tr-tr #17](https://github.com/dotnet/docs.tr-tr/issues/17) via [**ZenHub**](https://www.zenhub.com/)
