### ISSUE TITLE
Error 404 when clicking instructions on dotnet installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by assert-not-singularity** [dotnet/docs.de-de#193]
The German (de-de) documentation contains a link to instructions on the installation using a packet manager on Ubuntu 20.04.

However, when clicking the [link](https://docs.microsoft.com/de-de/dotnet/core/install/linux-package-manager-ubuntu-2004.md) in the list of contents, one is redirected to a 404 page. Note that this links contains a markdown ending (`.md`) while all other links in this tree level don't have a file ending at all. However, removing the `.md` at the end of the link leads to the 404 page as well.

![grafik](https://user-images.githubusercontent.com/26602675/80513280-1f778580-897f-11ea-91a5-d0ba594f0dec.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [.NET Core: Installieren von .NET Core auf Ubuntu 19.10 mit einem Paket-Manager](https://docs.microsoft.com/de-de/dotnet/core/install/linux-package-manager-ubuntu-1910#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @assert-not-singularity
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @assert-not-singularity 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

**I cannot repro your issue, can you please be more specific on which link is the one not working?
is the link also broken on the en-us page?**

Kind regards, 

Microsoft DOCS International Team

**Comment by assert-not-singularity** [comment]
Hello, @CeciAc 

Thanks for the quick response!

On the en-us page, the navigation does not contain a link for instructions on Ubuntu 20.04. This element only appears when switching from en-us to de-de. It should be visible when visiting https://docs.microsoft.com/de-de/dotnet/core/install/linux-package-manager-ubuntu-1910 and points to https://docs.microsoft.com/de-de/dotnet/core/install/linux-package-manager-ubuntu-2004.md which seems to be not valid.

**Comment by Thraka** [comment]
@CeciAc  This content was removed over the weekend. There must be a delay in getting out the localized updates?

**Comment by CeciAc** [comment]
Hello @assert-not-singularity 

Thanks for the clarification. 
As @Thraka says above, the German version is still to be updated after the translation round is over.
The delay is within the expected.

Kind regards,

Microsoft DOCS International Team
