### ISSUE TITLE
Error in UdpClient example 

### ISSUE THREAD

**Issue by decvs** [dotnet/docs.de-de#195]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2f7ffdc6-548a-fd6e-c4ed-27c2c497abb0
* Version Independent ID: 1c827898-93da-abc0-d0ae-6a8354c26409
* Content: [Verwenden von UDP-Diensten](https://docs.microsoft.com/de-de/dotnet/framework/network-programming/using-udp-services)
* Content Source: [docs/framework/network-programming/using-udp-services.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/network-programming/using-udp-services.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**
The example leads to the error: You must call the Bind method before performing this operation.

**Comment by srvbpigh** [comment]
Hello, @decvs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by karelz** [comment]
I couldn't reproduce the error -- I just tried the example (both listener and sender) from https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-udp-services and it worked just fine on .NET Core 3.1.

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #18251](https://github.com/dotnet/docs/issues/18251) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @decvs, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/18251. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
