### ISSUE TITLE
Some misleading terms in German version

### ISSUE THREAD

**Issue by Grinseteddy** [dotnet/docs.de-de#196]
Dear Ladies and Gentlemen, 
Thank you very much for the great content. Obviously, you used some automat for translation. A sidecar in German is called "Beiwagen". Something with "Seitigen Fahrzeug" is quite funny and misleading.
Regards Annegret

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0e5c1d5f-c051-6dbe-be7e-f9575d2e91ae
* Version Independent ID: 9862da8f-017c-f632-4f43-33abfd57ca59
* Content: [Service Mesh-Kommunikationsinfrastruktur](https://docs.microsoft.com/de-de/dotnet/architecture/cloud-native/service-mesh-communication-infrastructure#feedback)
* Content Source: [docs/architecture/cloud-native/service-mesh-communication-infrastructure.md](https://github.com/dotnet/docs.de-de/blob/live/docs/architecture/cloud-native/service-mesh-communication-infrastructure.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @Grinseteddy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Hello @Grinseteddy :

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

@JasonCard
