### ISSUE TITLE
--all-but <VERSIONS> Syntax ist nicht erklärt

### ISSUE THREAD

**Issue by smuehlst** [dotnet/docs.de-de#197]
Es wird nicht beschrieben, in welcher Form <VERSIONS> angegeben werden muss, wenn man mehrere Versionen angeben möchte:

```
--all-but <VERSIONS>

Removes all .NET Core SDKs and runtimes, except those versions specified.
```

Es funktioniert nicht, die Versionen durch Kommata zu trennen:

```
> dotnet-core-uninstall dry-run --all-but 2.1.514,2.1.202 --sdk
The specified version is not valid: "2.1.514,2.1.202".
```

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 289d3b2b-8b21-d0a0-10fa-9a8b3fdb62ce
* Version Independent ID: 3145ef37-2a19-e3ca-ba78-95c2f1a41a6b
* Content: [Deinstallationstool - .NET Core](https://docs.microsoft.com/de-de/dotnet/core/additional-tools/uninstall-tool?tabs=windows)
* Content Source: [docs/core/additional-tools/uninstall-tool.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/additional-tools/uninstall-tool.md)
* Product: **dotnet-core**
* GitHub Login: @sfoslund
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @smuehlst
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
