### ISSUE TITLE
Wo finde ich den Abschnitt "Nächste Schritte"?

### ISSUE THREAD

**Issue by AndreasKranzl** [dotnet/docs.de-de#200]
Im Text steht zwar:
Über den Abschnitt „Nächste Schritte“ gelangen Sie wieder zu diesen Tutorials.

Allerdings ist kein Link mit diesem Namen zu finden.
MfG
AK

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 67ff1559-a7c6-9c97-e543-298fbf63f57f
* Version Independent ID: ec7a656b-a94e-7d88-5162-32e931f2e094
* Content: [Datensammlungen – Einführung in das interaktive C#-Tutorial](https://docs.microsoft.com/de-de/dotnet/csharp/tutorials/intro-to-csharp/list-collection?tutorial-step=1)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/list-collection.yml](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/tutorials/intro-to-csharp/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @AndreasKranzl
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @AndreasKranzl 
Wir freuen uns über Ihren Kommentar und bemühen uns, Ihre Erfahrungen mit docs.microsoft.com zu verbessern. Wir benötigen jedoch weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern?
**cannot repro**

Mit freundlichen Grüßen
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hallo, @AndreasKranzl , 

Wir möchten nochmals auf unseren vorherigen Kommentar zurückkommen. Wir benötigen weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern? 

Mit freundlichen Grüßen 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @AndreasKranzl 
Nochmals vielen Dank für Ihren Kommentar.
Leider fehlen uns immer noch Informationen und wir können Ihr Feedback nicht bearbeiten. Wir schließen dieses GitHub-Problem jetzt, möchten Sie aber ermutigen, in Zukunft weiteres Feedback zu geben.
Mit freundlichen Grüßen
Microsoft DOCS International Team
