### ISSUE TITLE
Clean Code Violation in Code Snippet

### ISSUE THREAD

**Issue by Bruellhusten** [dotnet/docs.de-de#204]
Dears, 

```
    public void AddOrderItem(int productId, string productName,
                            decimal unitPrice, decimal discount,
                            string pictureUrl, int units = 1)
    {
        //...
        // Domain rules/logic for adding the OrderItem to the order
        // ...

        var orderItem = new OrderItem(productId, productName, unitPrice, discount, pictureUrl, units);

        _orderItems.Add(orderItem);

    }
```

this code example is a direct violation of Clean Code. I see the benefit of the Application layer not needing to know how to create an OrderItem, but solving this by giving each property of OrderItem in one by one is an anti-pattern. In this example it may still be not too "smelly", but what if OrderItem is a bigger object? Would you pass 30 properties one by one as parameters into that method?
Intuitively I would either write the method as
`AddOrderItem(OrderItem orderItem)`
if there is no domain rules for adding these, 
OR use a class
`AddOrderItem(AddOrderItemCommand command)`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 49c9fdb0-f078-2030-204d-67d016b22c8d
* Version Independent ID: 43bd7af4-f92e-f866-6725-b3c1b4e6afdb
* Content: [Implementieren eines Microservicedomänenmodells mit .NET Core](https://docs.microsoft.com/de-de/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md](https://github.com/dotnet/docs.de-de/blob/live/docs/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#21607
