### ISSUE TITLE
Missing example of how to connect to other apis

### ISSUE THREAD

**Issue by AndiRudi** [dotnet/docs.de-de#205]
I think one example is missing here. At least I couldnt find that. 

Let's assume you already have a microservice infrastructure with several services and authentication with identity server. Now you want to integrate with external services. That means you will create a page for integrations where users can select several other systems to integrate with. Usually there will be a button like "intergrate with x" and then you are redirected to x to login and get an access token and refresh token. From then on the integration is active and our service can use the tokens to access the external system. 

Questions around this case are:
- How do you do that? Is it possible with the asp.net identity only or is identity server needed?
- Where do you store the tokens? Do you need to go through identity server or is this implemented in another service?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d926868f-5446-63c6-75c0-ba879879f4b5
* Version Independent ID: ff9b78ce-a923-e763-08d5-c31cbb6a1f0e
* Content: [Sichern von .NET-Microservices und Webanwendungen](https://docs.microsoft.com/de-de/dotnet/architecture/microservices/secure-net-microservices-web-applications/)
* Content Source: [docs/architecture/microservices/secure-net-microservices-web-applications/index.md](https://github.com/dotnet/docs.de-de/blob/live/docs/architecture/microservices/secure-net-microservices-web-applications/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @mjrousos
* Microsoft Alias: **nanil**

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#21608
