### ISSUE TITLE
Übersetzungsfehler: "Kostenlos" anstatt "Frei"

### ISSUE THREAD

**Issue by thestevexyz** [dotnet/docs.de-de#208]
In der Tabelle bei dem Abschnitt "Grundlagen des Arbeitsspeichers" steht ganz oben "Kostenlos". In der Englischen Version steht allerdings "Free", also richtig übersetzt "Frei". "Free" heißt zwar im Englischen auch Kostenlos, allerdings müsste es in diesem Fall auf Deutsch "Frei" heißen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d8948cf5-0aec-308c-8046-965cc15763b2
* Version Independent ID: a30a0be5-b741-2a9c-e997-55d6d9960ca9
* Content: [Grundlagen der Garbage Collection](https://docs.microsoft.com/de-de/dotnet/standard/garbage-collection/fundamentals)
* Content Source: [docs/standard/garbage-collection/fundamentals.md](https://github.com/dotnet/docs.de-de/blob/live/docs/standard/garbage-collection/fundamentals.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@thestevexyz Danke schon!
