### ISSUE TITLE
Text contains *s and _s

### ISSUE THREAD

**Issue by Trolldemorted** [dotnet/docs.de-de#209]
![grafik](https://user-images.githubusercontent.com/10261186/98485926-537b0f80-221a-11eb-9e0e-50c0da8c80f2.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [Neuerungen in C# 9.0 – C#-Leitfaden](https://docs.microsoft.com/de-de/dotnet/csharp/whats-new/csharp-9)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@Trolldemorted Thanks for letting us know. This should be fixed by #209 and the changes will be visible in a couple days.
