### ISSUE TITLE
Async Sample Detail (no serious complaint)

### ISSUE THREAD

**Issue by Abudinka** [dotnet/docs.de-de#211]
Hallo, 

little bit of feedback towards the breakfast example in the c# Async Example. Although the sampe explains the concept really good, there is still no point in purring the coffee first of all, because it would still be cold by the time the breakfast ist done unless you drink the coffee async as well.

sorry for being silly

regards Abudinka

[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchrone Programmierung in C#](https://docs.microsoft.com/de-de/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@Abudinka Thanks for the comic relief!
