### ISSUE TITLE
C# Code not available on german site(de-de)

### ISSUE THREAD

**Issue by Nutzernam3** [dotnet/docs.de-de#215]
[Hier Feedback eingeben]
DE: C# Code für deutsche Seite (de-de) nicht verfügbar.
EN: C# Code not available on german site(de-de) 

https://docs.microsoft.com/de-de/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [Serialisieren und Deserialisieren von JSON mit C# – .NET](https://docs.microsoft.com/de-de/dotnet/standard/serialization/system-text-json-how-to)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs.de-de/blob/live/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@JasonCard Snippet names were changed in a PR that made structural changes to this article, splitting the article up into several smaller articles (https://github.com/dotnet/docs/pull/21626) -- how long would it normally take for changes like this to be propagated to localized versions?

**Comment by JasonCard** [comment]
@tdykstra It can take up to 2 weeks as we're on a weekly cadence with loc handoff on Sundays. So update yesterday on Monday would be handed off to loc vendor on following Sunday and could take up to a week to be translated and handed back depending on the word count,

**Comment by tdykstra** [comment]
@Nutzernam3 Thanks for reporting this. The code snippets should automatically show up in less than 2 weeks, and meanwhile you can find them in the English versions of the pages.
