### ISSUE TITLE
No Examples

### ISSUE THREAD

**Issue by Q-Sharp** [dotnet/docs.de-de#216]
Examples are empty....

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [Serialisieren und Deserialisieren von JSON mit C# – .NET](https://docs.microsoft.com/de-de/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-core-3-1)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs.de-de/blob/live/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
This is a temporary result of updates to the English version of the article -- within two weeks the changes should get propagated to the localized versions, including de-de.  Until then the code is available in the en-us version of the article.

**Comment by Q-Sharp** [comment]
Okay thank you! 
Maybe it's helpful for anyone finding this issue: It won't help to only use the small slider to see the English version, you have to change the url from (de-de) to (en-us).
