### ISSUE TITLE
Incorrect backslash on csc command line options reference list

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/docs.de-de#25]
On https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/compiler-options/listed-alphabetically there are `\` added in front of the command line args:

![image](https://user-images.githubusercontent.com/1376924/26859193-5ca3add8-4b36-11e7-9651-392ca0153ae9.png)

The English version at https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-alphabetically doesn't have those.

**Comment by akoeplinger** [comment]
@guardrex can you help route this to the correct place? should I have opened the issue in the main docs repo?

**Comment by GuardRex** [comment]
I moved it to https://github.com/dotnet/docs/issues/2462

You can close here, and I'll get to that soon.

**Comment by akoeplinger** [comment]
Thanks!
