### ISSUE TITLE
Weird sentence after translation

### ISSUE THREAD

**Issue by daniel-lerch** [dotnet/docs.de-de#72]
The last point of the first passage is not translated correctly. It could be:

✓ GGF. für Klassen, die zwar selbst keine verwalteten Ressourcen oder verwerfbare Objekte aufnehmen, aber wahrscheinlich Untertypen haben, die dies tun, das grundlegende Dispose-Muster implementieren.

Ein hervorragendes Beispiel dafür ist die `System.IO.Stream` Klasse. Obwohl es eine abstrakte Basisklasse ist, die keinerlei Ressourcen enthält, die meisten ihrer Unterklassen aber solche Ressourcen enthalten, implementiert sie aus diesem Grund das Dispose-Muster.

There are many more grammar mistakes in the german text, but this one is worst.

**Comment by CeciAc** [comment]
Hello @daniel-lerch 
Thank you for your feedback, we'll check this with our linguistic team.
Could you please specify the URL where you found this error?

Kind regards,
Microsoft DOCS International Team

**Comment by daniel-lerch** [comment]
Sorry, I totally forgot to specify the page.
You can find the article about the dispose pattern [here](https://docs.microsoft.com/de-de/dotnet/standard/design-guidelines/dispose-pattern).
The associated file in this repo is located [here](https://github.com/dotnet/docs.de-de/blob/live/docs/standard/design-guidelines/dispose-pattern.md)

Regards,
Daniel

**Comment by CeciAc** [comment]
Hello, @daniel-lerch , 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
