### ISSUE TITLE
404 error on link to solution

### ISSUE THREAD

**Issue by dreyses11** [dotnet/docs.de-de#74]
In docs.de-de/blob/live/docs/csharp/quick-starts/branches-and-loops-local.md is a link to an solution, but the solution doesn‘t exist (or is wrong linked), so you are recieving an 404 error, when you try to open the link and get to the solution.
![image](https://user-images.githubusercontent.com/33466028/38108179-4b9cd9b4-3394-11e8-85bd-69317cee230d.png)

**Comment by mairaw** [comment]
Issue moved to [dotnet/docs #4821](https://github.com/dotnet/docs/issues/4821) via [**ZenHub**](https://www.zenhub.com/)
