### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by DavidPrio** [dotnet/docs.de-de#78]
This is a test issue. Please disregard

**Comment by DavidPrio** [comment]
@maattie @flammeverte @tobrej can you see this?

**Comment by maattie** [comment]
I can see this, yes

Mariana Attie | Associate Project Manager
Moravia IT, LLC,
Monterey, CA 93940, USA
maattie@moravia.com<mailto:maattie@moravia.com> | moravia.com<http://www.moravia.com/> | Mariana.Attie.Moravia (skype)

This e-mail may contain proprietary information some or all of which may be legally privileged. It is for the intended recipient only. If an addressing or transmission error has misdirected this e-mail, please notify the author by replying to this e-mail and destroy this e-mail, message and attached document. If you are not the intended recipient you must not use, disclose, distribute, copy, or print this e-mail.

**Comment by flammeverte** [comment]
I confirm I can see this.

**Comment by DavidPrio** [comment]
Example #please-translate
