### ISSUE TITLE
Rechtschreibfehler

### ISSUE THREAD

**Issue by kapppi** [dotnet/docs.de-de#84]
"Ein struct-Typ ist ein ein Werttyp, der in der Regeln verwendet wird,..." // in der Regel...

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7df28ed8-1e6a-50a4-0678-5a368a655bc4
* Version Independent ID: 63a655e2-1eb6-d074-0f71-746ad61ca206
* Content: [struct (C#-Referenz)](https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/keywords/struct#feedback)
* Content Source: [docs/csharp/language-reference/keywords/struct.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/language-reference/keywords/struct.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hallo, @kapppi, 

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hallo, @kapppi ,

Vielen Dank für Ihr   Feedback.

unsere Sprachexperten haben   sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr   Feedback implementiert und im aktualisierten Artikel auf der   Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/keywords/struct.

Vielen Dank für Ihren Beitrag   zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen   Artikeln abgeben.

Mit freundlichen Grüßen
das Microsoft DOCS   International Team
