### ISSUE TITLE
Please use other automatic translation tool

### ISSUE THREAD

**Issue by mkauli** [dotnet/docs.de-de#87]
Given following sentence example from "Names of Properties": Unlike other members, properties should be given noun phrase or adjective names. That is because a property refers to data, and the name of the property reflects that. PascalCasing is always used for property names.

Automatic translation from Microsoft: Im Gegensatz zu anderen Mitgliedern Eigenschaften nominaler Ausdruck oder adjektivische Namen Unternehmensservern benötigen. Grund hierfür eine Eigenschaft bezieht sich auf Daten und der Namen der Eigenschaft angibt, ist. PascalCasing wird immer für Eigenschaftennamen verwendet.

Automatic translation of Google-Translator: Im Gegensatz zu anderen Mitgliedern sollten Eigenschaften eine Nominalphrase oder Adjektivnamen erhalten. Dies liegt daran, dass eine Eigenschaft auf Daten verweist und der Name der Eigenschaft dies widerspiegelt. PascalCasing wird immer für Eigenschaftsnamen verwendet.

From my point of view there are two options: 1.) Disable automatic translation - cause my eyes hurt when I see that :-)
2.) cooperate with Google - use their translation tool 

Best regards

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1cd21cac-a7e8-13ca-d940-3447312871ca
* Version Independent ID: 7f3307e9-5563-e28f-cdad-9b6e33358c6b
* Content: [Namen von Typmembern](https://docs.microsoft.com/de-de/dotnet/standard/design-guidelines/names-of-type-members)
* Content Source: [docs/standard/design-guidelines/names-of-type-members.md](https://github.com/dotnet/docs.de-de/blob/live/docs/standard/design-guidelines/names-of-type-members.md)
* Product: **.net**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
Hello, @mkauli ,  
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages [Namen von Typmembern](https://docs.microsoft.com/de-de/dotnet/standard/design-guidelines/names-of-type-members).  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
