### ISSUE TITLE
Runtime does not ignore missing file specified via "file" attribute 

### ISSUE THREAD

**Issue by Krumelur** [dotnet/docs.de-de#88]
In the paragraph about the "file" attribute you say: "Note that the runtime ignores the attribute if the specified file can not be found."
Building an app on VSTS I cannot verify this and I'm getting an error:

Microsoft.Web.Publishing.targets(2603,5): Error : Copying file PrivateAppSettings.config to obj\Debug\Package\PackageTmp\PrivateAppSettings.config failed. Could not find file 'PrivateAppSettings.config'.
Process 'msbuild.exe' exited with code '1'.

Here's an excerpt of my web.config:

&lt;appSettings file="PrivateAppSettings.config"&gt;
		&lt;add key="ClientId" value="xxxxxxxxxxxxxxx" /&gt;
&lt;/appSettings&gt;

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ea24ffb0-1e4a-4c73-c566-18b67e3bd69c
* Version Independent ID: 1d1c4a41-9dfd-82f9-ed0c-993c45b16b25
* Content: [&lt;](https://docs.microsoft.com/de-de/dotnet/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration)
* Content Source: [docs/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration.md)
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

**Comment by Krumelur** [comment]
Ignore. My bad. The error was about copying the file and not really related to the attribute.

**Comment by gosali** [comment]
Hello, @Krumelur , 

Thank you for your feedback. 

We are actively reviewing your comments please do not hesitate to submit another feedback if needed. 

Kind regards, 
Microsoft DOCS International Team
