### ISSUE TITLE
Einführungskurs in C#

### ISSUE THREAD

**Issue by Mammut1966** [dotnet/docs.de-de#89]
Der Einführungskurs in C# ist echt super gemacht, vielen Dank :-)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8b514dfb-f00b-8ac3-4027-7a28770f959e
* Version Independent ID: 7db3af08-9406-10da-76a1-1f8db30d1d2d
* Content: [Interaktives Tutorial „Hello World“: C#-Schnellstarts](https://docs.microsoft.com/de-de/dotnet/csharp/quick-starts/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/hello-world.yml](https://github.com/dotnet/docs.de-de/blob/live-sxs/docs/csharp/quick-starts/hello-world.yml)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by DavidPrio** [comment]
Hallo, @Mammut1966 , 

vielen Dank für Ihr Feedback. Es freut uns, dass Sie mir unserer Dokumentation zufrieden sind. 
Sie können gerne weiterhin Feedback abgeben, damit wir die Servicequalität kontinuierlich verbessern können. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
