### ISSUE TITLE
Befehlszeile wird nicht akzeptiert

### ISSUE THREAD

**Issue by jk-ware** [dotnet/docs.de-de#90]
in den Projekteigenschaften von Visual Studio 2017 wird unter Buildereignisse in der Befehlszeile für Präbuildereignis nach der Befehlseingabe von /r:TypeStructs=Mono.Android.dll von dem Compiler die Meldung ausgegeben, dass dieser Befehl mit dem Code 123 beendet wurde.

Nachfolgende Bezugnahmen auf den externen Alias TypeStructs verursachen die Fehlermeldung, dass dieser Alias nicht in einer /reference-Option angegeben wurde.

Welcher Fehler liegt hier vor oder was läuft nicht richtig?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 42871bc9-b130-8acf-11e1-bca2ac6c33f8
* Version Independent ID: fc5187e6-8cad-b6b9-d5b4-fa5d847bcda9
* Content: [extern-Alias (C#-Referenz)](https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/keywords/extern-alias?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(alias_CSharpKeyword)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/keywords/extern-alias.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/language-reference/keywords/extern-alias.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gosali** [comment]
Hallo, @jk-ware ,  
 
Vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht.  
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite.   

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln.  
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   
 

Mit freundlichen Grüßen  
das Microsoft DOCS International Team

**Comment by jk-ware** [comment]
Ich betrachte diese Dokumentation als fehlerhaft. 

Weshalb mein Feedback hierzu jetzt geschlossen wurde, ist mir nicht klar.
