### ISSUE TITLE
.NET Framework 3.5 erforderlich, wenn neuere Frameworks installiert sind?

### ISSUE THREAD

**Issue by ber999** [dotnet/docs.de-de#98]
Weshalb ist das .NET Framework 3.5 noch erforderlich, wenn neuere Frameworks installiert sind?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Installieren von .NET Framework 3.5 auf Windows 10, Windows 8.1 und Windows 8](https://docs.microsoft.com/de-de/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/install/dotnet-35-windows-10.md)
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by LisandroSu** [comment]
Hallo, @ber999 

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
